---
- name: Include OS-Specific variables
  include_vars: "{{ ansible_system }}.yml"

- import_tasks: facts/set-java-facts.yml
  become: true

- import_tasks: facts/set-dyna-facts.yml
  become: true

- include_tasks: dependencies/install-dependencies-{{ ansible_pkg_mgr }}.yml

- include: user/install-dynatrace-user-{{ ansible_pkg_mgr }}.yml

- include: user/install-dynatrace-user-Linux.yml
  when:  "ansible_pkg_mgr == 'yum' or  ansible_pkg_mgr == 'apt'"

- include_tasks: agent/install-dynatrace-agent-{{ ansible_pkg_mgr }}.yml

# - include: dependencies/remove-dependencies-{{ ansible_pkg_mgr }}.yml

# DONE:0 ensure full solaris support
# TODO:0 TEST IDEMPOTENCE
# TODO:20 ensure tests run on docker
# TODO:10 convert to molecule
# BACKLOG:40 windows support
